import Link from "next/link";
import { ChevronDown, Save } from "lucide-react";
import { DynamicSettingsListEnhancer } from "@/components/admin/dynamic-settings-list-enhancer";
import { MediaPickerEnhancer } from "@/components/admin/media-path-picker";
import { requireAdmin } from "@/features/admin-auth/session";
import { adminMediaLibrary } from "@/features/content/queries";
import { updateOwnerContentSettings } from "@/features/site-settings/owner-content-actions";
import { getOwnerContentSettings } from "@/features/site-settings/owner-content";

export const dynamic = "force-dynamic";
type Media = Awaited<ReturnType<typeof adminMediaLibrary>>;
function Summary({ index, title, text }: { index: string; title: string; text: string }) { const help = text.startsWith("Σύρετε τις ενότητες") ? "Χρησιμοποιήστε τα κουμπιά Πάνω/Κάτω ή απενεργοποιήστε όσες ενότητες δεν θέλετε να εμφανίζονται." : text; return <summary><span>{index}</span><div><h2>{title}</h2><p>{help}</p></div><ChevronDown aria-hidden="true" /></summary>; }
const homepageSectionLabels = { intro: "Εισαγωγή", services: "Η Alana από κοντά", news: "Τελευταία νέα", testimonials: "Testimonials", sponsors: "Χορηγοί", contact: "Τελική επικοινωνία" } as const;

export default async function OwnerSiteSettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  await requireAdmin();
  const [settings, media] = await Promise.all([getOwnerContentSettings(), adminMediaLibrary(120)]);
  const saved = (await searchParams).saved === "1";
  const { site, homepage } = settings;
  return <main className="admin-content admin-site-settings">
    <header><div><p className="eyebrow">ALANA FC · ΔΙΑΧΕΙΡΙΣΗ</p><h1>Ιστοσελίδα</h1><p>Επιλέξτε πρώτα τη σελίδα και μετά την ενότητα που θέλετε να αλλάξετε.</p></div><div className="admin-content__header-actions"><Link href="/" target="_blank">Προβολή site</Link><Link href="/admin">Πίσω</Link></div></header>
    {saved ? <p className="admin-media__success" role="status">Οι αλλαγές αποθηκεύτηκαν και δημοσιεύτηκαν.</p> : null}
    <form action={updateOwnerContentSettings} className="admin-editor admin-site-settings__form admin-settings-accordion">
      <datalist id="owner-media-options">{(media as Media).map((item) => <option key={item.externalId} value={item.src}>{item.alt}</option>)}</datalist>
      <DynamicSettingsListEnhancer />
      <MediaPickerEnhancer media={(media as Media).map((item) => ({ externalId: item.externalId, src: item.src, alt: item.alt, filename: item.filename, width: item.width, height: item.height }))} />

      <details className="admin-settings-group">
        <Summary index="01" title="Αρχική" text="Slider, ενότητες, testimonials και χορηγοί." />
        <div className="admin-settings-group__content">
          <details className="admin-settings-panel"><Summary index="01.0" title="Σειρά ενοτήτων" text="Σύρετε τις ενότητες για να αλλάξετε τη σειρά τους ή απενεργοποιήστε όσες δεν θέλετε να εμφανίζονται." /><input type="hidden" name="homepageSectionCount" value={homepage.sectionOrder.length} /><div className="admin-repeat-list admin-repeat-list--sections">{homepage.sectionOrder.map((section, index) => <fieldset key={section.id}><legend>Ενότητα {index + 1}</legend><input type="hidden" name={`homepageSection.${index}.id`} value={section.id} /><label className="admin-setting-toggle"><input type="checkbox" name={`homepageSection.${index}.enabled`} defaultChecked={section.enabled} /> {homepageSectionLabels[section.id]}</label></fieldset>)}</div><div className="admin-site-settings__fields"><label>Μικρός τίτλος νέων<input name="homepage.newsEyebrow" defaultValue={homepage.newsEyebrow} required /></label><label>Τίτλος νέων<input name="homepage.newsTitle" defaultValue={homepage.newsTitle} required /></label><label>Κουμπί νέων<input name="homepage.newsButtonLabel" defaultValue={homepage.newsButtonLabel} required /></label><label className="is-wide">Μήνυμα όταν δεν υπάρχουν νέα<textarea name="homepage.newsEmptyText" rows={2} defaultValue={homepage.newsEmptyText} required /></label><label>Μικρός τίτλος «Η Alana από κοντά»<input name="homepage.servicesEyebrow" defaultValue={homepage.servicesEyebrow} required /></label><label>Τίτλος «Η Alana από κοντά»<input name="homepage.servicesTitle" defaultValue={homepage.servicesTitle} required /></label><label>Μικρός τίτλος testimonials<input name="homepage.testimonialsEyebrow" defaultValue={homepage.testimonialsEyebrow} required /></label><label>Τίτλος testimonials<input name="homepage.testimonialsTitle" defaultValue={homepage.testimonialsTitle} required /></label><label>Μικρός τίτλος χορηγών<input name="homepage.sponsorsEyebrow" defaultValue={homepage.sponsorsEyebrow} required /></label><label>Τίτλος χορηγών<input name="homepage.sponsorsTitle" defaultValue={homepage.sponsorsTitle} required /></label></div></details>
          <details className="admin-settings-panel"><Summary index="01.1" title="Hero slider" text="Εικόνες, τίτλοι και σύνδεσμοι των slides." /><input type="hidden" name="heroCount" value={homepage.heroSlides.length} /><div className="admin-repeat-list">{homepage.heroSlides.map((slide, index) => <fieldset key={`${slide.href}-${index}`}><legend>Slide {index + 1}</legend><label className="admin-setting-toggle"><input type="checkbox" name={`hero.${index}.enabled`} defaultChecked={slide.enabled} /> Ενεργό slide</label><label>Μικρός τίτλος<input name={`hero.${index}.eyebrow`} defaultValue={slide.eyebrow} required /></label><label className="is-wide">Τίτλος<input name={`hero.${index}.title`} defaultValue={slide.title} required /></label><label className="is-wide">Περιγραφή<textarea name={`hero.${index}.description`} rows={3} defaultValue={slide.description} required /></label><label>Κουμπί<input name={`hero.${index}.button`} defaultValue={slide.button} required /></label><label>Σύνδεσμος<input name={`hero.${index}.href`} defaultValue={slide.href} required /></label><label>Εικόνα<input list="owner-media-options" name={`hero.${index}.image`} defaultValue={slide.image} required /></label><label>SEO περιγραφή εικόνας<input name={`hero.${index}.alt`} defaultValue={slide.alt} required /></label></fieldset>)}</div></details>

          <details className="admin-settings-panel"><Summary index="01.2" title="Εισαγωγή & νέα" text="Η ενότητα μετά το slider και τα τελευταία άρθρα." /><div className="admin-site-settings__fields"><label>Μικρός τίτλος<input name="homepage.introEyebrow" defaultValue={homepage.introEyebrow} required /></label><label>Τίτλος<input name="homepage.introTitle" defaultValue={homepage.introTitle} required /></label><label className="is-wide">Κείμενο<textarea name="homepage.introText" rows={3} defaultValue={homepage.introText} required /></label><label>Κουμπί<input name="homepage.introButtonLabel" defaultValue={homepage.introButtonLabel} required /></label><label>Σύνδεσμος κουμπιού<input name="homepage.introButtonHref" defaultValue={homepage.introButtonHref} required /></label><label>Πλήθος τελευταίων νέων<input type="number" min="3" max="12" name="homepage.latestPostsCount" defaultValue={homepage.latestPostsCount} required /></label></div></details>

          <details className="admin-settings-panel"><Summary index="01.3" title="Η Alana από κοντά" text="Προπονητές, εγκαταστάσεις και Sports Club." /><input type="hidden" name="serviceCount" value={homepage.services.length} /><div className="admin-repeat-list">{homepage.services.map((item, index) => <fieldset key={`${item.title}-${index}`}><legend>Κάρτα {index + 1}</legend><label className="admin-setting-toggle"><input type="checkbox" name={`service.${index}.enabled`} defaultChecked={item.enabled} /> Ενεργή</label><label>Τίτλος<input name={`service.${index}.title`} defaultValue={item.title} required /></label><label>Σύνδεσμος<input name={`service.${index}.href`} defaultValue={item.href} required /></label><label>Κείμενο κουμπιού<input name={`service.${index}.buttonLabel`} defaultValue={item.buttonLabel} required /></label><label>Εικόνα<input list="owner-media-options" name={`service.${index}.image`} defaultValue={item.image} required /></label><label className="is-wide">Περιγραφή<textarea name={`service.${index}.description`} rows={3} defaultValue={item.description} required /></label><label className="is-wide">Λέξεις-κλειδιά<textarea name={`service.${index}.keywords`} rows={3} defaultValue={item.keywords.join("\n")} required /></label></fieldset>)}</div></details>

          <details className="admin-settings-panel"><Summary index="01.4" title="Testimonials" text="Οι μαρτυρίες που εμφανίζονται στην αρχική." /><input type="hidden" name="testimonialCount" value={homepage.testimonials.length} /><div className="admin-repeat-list">{homepage.testimonials.map((item, index) => <fieldset key={`${item.name}-${index}`}><legend>Μαρτυρία {index + 1}</legend><label className="admin-setting-toggle"><input type="checkbox" name={`testimonial.${index}.enabled`} defaultChecked={item.enabled} /> Ενεργή</label><label>Όνομα<input name={`testimonial.${index}.name`} defaultValue={item.name} required /></label><label>Ιδιότητα<input name={`testimonial.${index}.role`} defaultValue={item.role} required /></label><label>Εικόνα<input list="owner-media-options" name={`testimonial.${index}.image`} defaultValue={item.image} required /></label><label className="is-wide">Κείμενο<textarea name={`testimonial.${index}.quote`} rows={4} defaultValue={item.quote} required /></label></fieldset>)}</div></details>

          <details className="admin-settings-panel"><Summary index="01.5" title="Χορηγοί" text="Λογότυπο και website κάθε συνεργάτη." /><input type="hidden" name="sponsorCount" value={homepage.sponsors.length} /><div className="admin-repeat-list">{homepage.sponsors.map((item, index) => <fieldset key={`${item.name}-${index}`}><legend>Χορηγός {index + 1}</legend><label className="admin-setting-toggle"><input type="checkbox" name={`sponsor.${index}.enabled`} defaultChecked={item.enabled} /> Ενεργός</label><label>Όνομα<input name={`sponsor.${index}.name`} defaultValue={item.name} required /></label><label>Website<input type="url" name={`sponsor.${index}.href`} defaultValue={item.href} required /></label><label>Λογότυπο<input list="owner-media-options" name={`sponsor.${index}.image`} defaultValue={item.image} required /></label></fieldset>)}</div></details>

          <details className="admin-settings-panel"><Summary index="01.6" title="Τελική επικοινωνία" text="Το τελευταίο κάλεσμα επικοινωνίας στην αρχική." /><div className="admin-site-settings__fields"><label>Μικρός τίτλος<input name="homepage.contactEyebrow" defaultValue={homepage.contactEyebrow} required /></label><label>Τίτλος<input name="homepage.contactTitle" defaultValue={homepage.contactTitle} required /></label><label className="is-wide">Κείμενο<textarea name="homepage.contactText" rows={3} defaultValue={homepage.contactText} required /></label><label>Κουμπί<input name="homepage.contactButtonLabel" defaultValue={homepage.contactButtonLabel} required /></label></div></details>
        </div>
      </details>

      <Link className="admin-settings-route-card" href="/admin/site/registrations"><span>02</span><div><h2>Εγγραφές</h2><p>Τίτλοι, τμήματα K6–K16 και επιλογές της φόρμας.</p></div><span aria-hidden="true">→</span></Link>

      <Link className="admin-settings-route-card" href="/admin/site/pages"><span>03</span><div><h2>Εσωτερικές σελίδες</h2><p>Ακαδημία, προπονητές, εγκαταστάσεις, Sports Club και επικοινωνία.</p></div><span aria-hidden="true">→</span></Link>

      <Link className="admin-settings-route-card" href="/admin/site/documents"><span>04</span><div><h2>Χρήσιμα έγγραφα</h2><p>PDF, σειρά καρτών, ενεργοποίηση και κουμπιά προβολής.</p></div><span aria-hidden="true">→</span></Link>

      <details className="admin-settings-group">
        <Summary index="03" title="Γενικά στοιχεία" text="Επικοινωνία, menu και footer σε όλο το site." />
        <div className="admin-settings-group__content">
          <details className="admin-settings-panel"><Summary index="03.1" title="Στοιχεία επικοινωνίας" text="Τηλέφωνα, email και διεύθυνση που εμφανίζονται δημόσια." /><div className="admin-site-settings__fields"><label>Email<input type="email" name="site.email" defaultValue={site.email} required /></label><label>Διεύθυνση<input name="site.address" defaultValue={site.address} required /></label><label>Κινητό για σύνδεσμο<input name="site.phone" defaultValue={site.phone} required /></label><label>Κινητό όπως εμφανίζεται<input name="site.phoneDisplay" defaultValue={site.phoneDisplay} required /></label><label>Σταθερό για σύνδεσμο<input name="site.landline" defaultValue={site.landline} required /></label><label>Σταθερό όπως εμφανίζεται<input name="site.landlineDisplay" defaultValue={site.landlineDisplay} required /></label></div></details>
          <details className="admin-settings-panel"><Summary index="03.2" title="Μενού & footer" text="Ονόματα, σύνδεσμοι, preview εικόνες και τελικό κάλεσμα." /><input type="hidden" name="navigationCount" value={site.navigation.length} /><div className="admin-repeat-list">{site.navigation.map((item, index) => <fieldset key={`${item.href}-${index}`}><legend>Σύνδεσμος {index + 1}</legend><label className="admin-setting-toggle"><input type="checkbox" name={`navigation.${index}.enabled`} defaultChecked={item.enabled} /> Ενεργός</label><label>Όνομα<input name={`navigation.${index}.label`} defaultValue={item.label} required /></label><label>Σύνδεσμος<input name={`navigation.${index}.href`} defaultValue={item.href} required /></label><label>Εικόνα preview<input list="owner-media-options" name={`navigation.${index}.image`} defaultValue={item.image} required /></label></fieldset>)}</div><div className="admin-site-settings__fields"><label>Μικρός τίτλος footer<input name="site.footerEyebrow" defaultValue={site.footerEyebrow} required /></label><label>Μεγάλος τίτλος footer<input name="site.footerTitle" defaultValue={site.footerTitle} required /></label><label>Κουμπί footer<input name="site.footerButtonLabel" defaultValue={site.footerButtonLabel} required /></label><label>Σύνδεσμος footer<input name="site.footerButtonHref" defaultValue={site.footerButtonHref} required /></label><label>Μεγάλο λογότυπο κειμένου<input name="site.footerWordmark" defaultValue={site.footerWordmark} required /></label></div></details>
        </div>
      </details>

      <div className="admin-site-settings__submit"><button type="submit"><Save aria-hidden="true" /> Αποθήκευση και δημοσίευση</button><p>Οι αλλαγές εμφανίζονται αμέσως. Τα στοιχεία σύνδεσης και email αποστολής δεν εκτίθενται εδώ.</p></div>
    </form>
  </main>;
}
