export const siteConfig = {
  name: "Alana FC Academy",
  shortName: "Alana FC",
  description: "Η επίσημη ιστοσελίδα της Alana FC Academy στην Αλεξανδρούπολη.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://alanafc.gr",
  socialImage: "/alana_fc_academy_images_wordpress/academy_alana_header_1.jpg",
  email: "f.c.alana@hotmail.com",
  phone: "+306974924194",
  phoneDisplay: "697 492 4194",
  landline: "+302551088355",
  landlineDisplay: "25510 88355",
  address: "Εργατικά, Παλαγιά, Αλεξανδρούπολη 681 32",
  mapDirectionsUrl: "https://www.google.com/maps/search/?api=1&query=Alana+FC+Academy+Palagia+Alexandroupoli+68132",
  mapEmbedUrl: "https://maps.google.com/maps?q=Alana%20FC%20Academy%20Palagia%20Alexandroupoli%2068132&z=16&output=embed",
  publicRoutes: [
    { href: "/", changeFrequency: "weekly", priority: 1 },
    { href: "/about-us", changeFrequency: "monthly", priority: 0.8 },
    { href: "/coaching-staff", changeFrequency: "monthly", priority: 0.8 },
    { href: "/our-facilities", changeFrequency: "monthly", priority: 0.8 },
    { href: "/sportclub-alana", changeFrequency: "monthly", priority: 0.8 },
    { href: "/news", changeFrequency: "weekly", priority: 0.9 },
    { href: "/eggrafes-2026-2027", changeFrequency: "weekly", priority: 0.9 },
    { href: "/contact-us", changeFrequency: "monthly", priority: 0.8 },
    { href: "/useful-documents", changeFrequency: "monthly", priority: 0.6 },
    { href: "/privacy", changeFrequency: "yearly", priority: 0.3 },
    { href: "/cookies", changeFrequency: "yearly", priority: 0.3 },
    { href: "/accessibility", changeFrequency: "yearly", priority: 0.3 },
  ],
  navigation: [
    { label: "Εγγραφές", href: "/eggrafes-2026-2027", image: "/alana_fc_academy_images_wordpress/eggrafes_11zon.jpeg" },
    { label: "Η Ακαδημία", href: "/about-us", image: "/alana_fc_academy_images_wordpress/academy_alana_header_2.jpg" },
    { label: "Οι Άνθρωποί μας", href: "/coaching-staff", image: "/alana_fc_academy_images_wordpress/alana_coach_hug.jpg" },
    { label: "Εγκαταστάσεις", href: "/our-facilities", image: "/alana_fc_academy_images_wordpress/alana_ghpedo_1.jpg" },
    { label: "Νέα", href: "/news", image: "/alana_fc_academy_images_wordpress/alana_fc_kids_gallery.jpg" },
    { label: "Επικοινωνία", href: "/contact-us", image: "/alana_fc_academy_images_wordpress/alana_corner_flag.jpg" },
  ],
  legalNavigation: [
    { label: "Απόρρητο", href: "/privacy" },
    { label: "Cookies", href: "/cookies" },
    { label: "Προσβασιμότητα", href: "/accessibility" },
  ],
} as const;
