import type { Metadata } from "next";
import Image from "next/image";
import { AnimatedLines, ClipReveal, ParallaxMedia } from "@/components/motion";
import { ContactForm } from "@/components/contact/contact-form";
import { PrivacyMap } from "@/components/contact/privacy-map";
import { publicPageMetadata } from "@/features/seo/public-metadata";
import { preferredMediaUrl, publicPageBySlug } from "@/features/content/queries";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = publicPageMetadata({ title: "Επικοινωνία", description: `Επικοινωνήστε με την Alana FC Academy στην ${siteConfig.address}.`, path: "/contact-us", image: "/alana_fc_academy_images_wordpress/alana_sportsclub_contact_us_1.jpg", imageAlt: "Το γήπεδο της Alana FC Academy στην Αλεξανδρούπολη" });
export const dynamic = "force-dynamic";
export default async function ContactPage() { const entry = await publicPageBySlug("contact-us"); const title = entry?.content.title || "Ας μιλήσουμε για το επόμενο παιχνίδι."; const intro = entry?.content.excerpt || "Για προπονήσεις, τμήματα, συνεργασίες ή οποιαδήποτε ερώτηση, η ομάδα μας είναι εδώ."; const heroImage = preferredMediaUrl(entry?.media ?? null) || "/alana_fc_academy_images_wordpress/alana_sportsclub_contact_us_1.jpg"; return <main id="main-content" className="contact-page"><section className="contact-hero"><div className="contact-hero__copy"><p className="eyebrow">Αλεξανδρούπολη · Ελλάδα</p><AnimatedLines as="h1"><span>{title}</span></AnimatedLines><AnimatedLines>{intro}</AnimatedLines></div><ClipReveal className="contact-hero__media"><ParallaxMedia strength={10}><Image src={heroImage} alt="Το γήπεδο της Alana FC Academy" fill priority sizes="(max-width: 767px) 100vw, 50vw" className="object-cover" /></ParallaxMedia></ClipReveal></section>{entry?.content.bodyHtml ? <section className="academy-destination__managed-copy"><header><AnimatedLines as="h2">Πληροφορίες επικοινωνίας</AnimatedLines><p className="eyebrow">Alana FC Academy</p></header><div className="content-body" dangerouslySetInnerHTML={{ __html: entry.content.bodyHtml }} /></section> : null}<section className="contact-main"><aside><p className="eyebrow">Άμεση επικοινωνία</p><h2>Βρείτε μας.</h2><div className="contact-details"><a href={`tel:${siteConfig.phone}`}><span>Κινητό</span><strong>{siteConfig.phoneDisplay}</strong></a><a href={`tel:${siteConfig.landline}`}><span>Σταθερό</span><strong>{siteConfig.landlineDisplay}</strong></a><a href={`mailto:${siteConfig.email}`}><span>Email</span><strong>{siteConfig.email}</strong></a><p><span>Διεύθυνση</span><strong>{siteConfig.address}</strong></p></div></aside><div><header><p className="eyebrow">Φόρμα επικοινωνίας</p><AnimatedLines as="h2">Στείλτε μας το μήνυμά σας.</AnimatedLines></header><ContactForm /></div></section><PrivacyMap /></main>; }
